### ISSUE TITLE
Lingua::AR::Tashkeel dependency declaration not sufficient

### ISSUE THREAD

**Issue by andk** [athreef/Encode-Arabic-Franco#1]
As per subject.

says 0.002 is required: https://metacpan.org/source/ATHREEF/Encode-Arabic-Franco-0.007/Makefile.PL#L20

says 0.4.0 is required: http://www.cpantesters.org/cpan/report/73774129

HTH&&Thanks,

**Comment by a3f** [comment]
This should fix it. Thanks for reporting. :)
